# Generated by Django 4.1 on 2022-08-18 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_workout', models.CharField(max_length=50, verbose_name='Название тренировки')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата теренировки')),
                ('exercise_name', models.CharField(max_length=50, verbose_name='Название упражнения')),
                ('number_of_approaches', models.IntegerField(verbose_name='Количество подходов')),
                ('amount_of_exercise', models.IntegerField(verbose_name='Количество упражнений')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Пройденая дистанция')),
                ('workout_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Время тренировки')),
                ('photo_workout', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото тренировки')),
                ('description', models.TextField(verbose_name='Описание тренировки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
