# Generated by Django 4.1 on 2022-08-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_category_task_trainprogram_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
