# Generated by Django 4.1 on 2022-09-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='likes',
            field=models.ManyToManyField(related_name='workout_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
