# Generated by Django 4.1 on 2022-08-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_workouts'),
        ('db', '0003_remove_task_author'),
    ]

    operations = [
    ]
