# Generated by Django 4.1 on 2022-08-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_merge_0002_workouts_0003_remove_task_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
