# Generated by Django 4.1 on 2022-08-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_user_managers_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='workouts',
            options={'verbose_name_plural': 'Workouts'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
