# Generated by Django 4.1 on 2022-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='example_photo',
            field=models.ImageField(blank=True, null=True, upload_to='task'),
        ),
    ]
